<div class="row">
	<div class="col-lg-12"><button type="button" class="btn btn-default" name="" onclick="sendEmail();"><span class="glyphicon glyphicon-email">Отправить</span></button></div>
</div><!-- /.row -->
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-title"><?php echo $controller->t->_("index_index_my_organizations"); ?></h2>
			</div>
			<div class="panel-body">
				<?php if(count($orgs) > 0) { ?>
					<div class="row">
						<?php foreach($orgs as $org) { ?>
							<div class="col-lg-2">
								<a href="#" class="thumbnail">
									<!--<img src="<?php //echo $org["img"]; ?>" alt="..." href="/organization/index?id=<?php //echo $org["id"]; ?>">-->
									<p class="text-center h4"><?php echo $org["name"]; ?></p>
								</a>
							</div>
						<?php } ?>
					</div><!-- /.row -->
				<?php } else { ?>
					<div class="row">
						<div class="col-lg-12">
							<p><?php echo $controller->t->_("index_index_no_organizations"); ?></p>
						</div>
					</div><!-- /.row -->
				<?php } ?>
			</div>
		</div>
	</div>
</div><!-- /.row -->
<?php //var_dump( $user); ?>
<?php //var_dump( $orgs); ?>


<script type="text/javascript"><!--

function sendEmail() {
	$.ajax({
		url: '/index/sendemail',
		dataType: 'json',
		method: 'get',
		beforeSend: function() {
				// показываем прогрессбар
		},
		complete: function() {
			// скрываем прогрессбар
		},			
		success: function(json) {
			console.log(json);
			handleAjaxSuccess(json.success)
			if(!handleAjaxError(json.error)) {
				//if(json.success.redirect) document.location = json.success.redirect;
			}
			
		},
		error: function(xhr, ajaxOptions, thrownError) {
			console.log(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
			handleAjaxError({
				messages: [{
					title: 'Ошибка обмена данными',
					msg: 'Ошибка обработки запроса на стороне сервера. Обратитесь в службу поддержки',
				}],
			});
		}
	});
}


//--></script>

