<script id="organization_template" type="text/x-jsrender">
<span></span>
<div class="container-fluid" id="{{:descriptor.local_data.container_id}}">
	<div class="row">
		<div class="pull-right">
			{{if !~inModal}}
				{{if descriptor.operations ~descriptor=descriptor}}
					{{for descriptor.operations tmpl="operation" /}}
				{{/if}}
				<button type="button" class="btn btn-default" data-dismiss="modal" onclick="location.reload();">Отмена</button>
			{{/if}}
			<div>&nbsp;</div>
		</div><!-- /.pull-right -->
	</div><!-- /.row -->
	<div class="row-fluid">
		<!-- Nav tabs -->
		<ul class="nav nav-pills" role="tablist">
			<li role="presentation" class="{{if !descriptor.filter_values['selected_tab'] || descriptor.filter_values['selected_tab'] == 'entity_tab_main'}}active{{/if}}"><a href="#entity_tab_main" aria-controls="entity_tab_main" role="tab" data-toggle="tab">Основная информация</a></li>
			
			{{if descriptor.scrollers && descriptor.scrollers.expenselist}}<li role="presentation" class="{{if descriptor.filter_values['selected_tab'] && descriptor.filter_values['selected_tab'] == descriptor.scrollers.expenselist.controllerNameLC}}active{{/if}}"><a href="#entity_tab_expenses_{{:descriptor.local_data.container_id}}" aria-controls="entity_tab_expenses" role="tab" data-toggle="tab">Расходы</a></li>{{/if}}
			{{if descriptor.scrollers && descriptor.scrollers.userlist}}<li role="presentation" class="{{if descriptor.filter_values['selected_tab'] && descriptor.filter_values['selected_tab'] == descriptor.scrollers.userlist.controllerNameLC}}active{{/if}}"><a href="#entity_tab_userlist_{{:descriptor.local_data.container_id}}" aria-controls="entity_tab_userlist" role="tab" data-toggle="tab">Пользователи</a></li>{{/if}}
			{{if descriptor.scrollers && descriptor.scrollers.organizationrequestlist}}<li role="presentation" class="{{if descriptor.filter_values['selected_tab'] && descriptor.filter_values['selected_tab'] == descriptor.scrollers.organizationrequestlist.controllerNameLC}}active{{/if}}"><a href="#entity_tab_organizationrequestlist_{{:descriptor.local_data.container_id}}" aria-controls="entity_tab_organizationrequestlist" role="tab" data-toggle="tab">Вопросы <span id="scroller_{{:descriptor.scrollers.organizationrequestlist.controllerNameLC}}_newCount" class="label {{if descriptor.scrollers.organizationrequestlist.newCount && descriptor.scrollers.organizationrequestlist.newCount > 0}}label-danger{{else}}label-success{{/if}}">{{:descriptor.scrollers.organizationrequestlist.newCount}}</span></a></li>{{/if}}
		</ul>	
		<!-- Tab panes -->
		<div class="tab-content">
			<div role="tabpanel" class="tab-pane {{if !descriptor.filter_values['selected_tab'] || descriptor.filter_values['selected_tab'] == 'entity_tab_main'}}active{{/if}}" id="entity_tab_main">
				<div class="container-fluid">
					<div class="row-fluid">&nbsp;</div>
					<div class="row-fluid">
						{{include tmpl = "entity_fields_form" /}}
					</div>
				</div>
			</div>
			{{if descriptor.scrollers && descriptor.scrollers.expenselist}}
				<div role="tabpanel" class="tab-pane {{if descriptor.filter_values['selected_tab'] && descriptor.filter_values['selected_tab'] == descriptor.scrollers.expenselist.controllerNameLC}}active{{/if}}" id="entity_tab_expenses_{{:descriptor.local_data.container_id}}">
					<div class="container-fluid">
						<div class="row-fluid">&nbsp;</div>
						<div class="row-fluid">
							<div id="placeholder_{{:descriptor.scrollers.expenselist.local_data.container_id}}"></div>
						</div>
					</div>
				</div>
			{{/if}}
			{{if descriptor.scrollers && descriptor.scrollers.userlist}}
				<div role="tabpanel" class="tab-pane {{if descriptor.filter_values['selected_tab'] && descriptor.filter_values['selected_tab'] == descriptor.scrollers.userlist.controllerNameLC}}active{{/if}}" id="entity_tab_userlist_{{:descriptor.local_data.container_id}}">
					<div class="container-fluid">
						<div class="row-fluid">&nbsp;</div>
						<div class="row-fluid">
							<div id="placeholder_{{:descriptor.scrollers.userlist.local_data.container_id}}"></div>
						</div>
					</div>
				</div>
			{{/if}}
			{{if descriptor.scrollers && descriptor.scrollers.organizationrequestlist}}
				<div role="tabpanel" class="tab-pane {{if descriptor.filter_values['selected_tab'] && descriptor.filter_values['selected_tab'] == descriptor.scrollers.organizationrequestlist.controllerNameLC}}active{{/if}}" id="entity_tab_organizationrequestlist_{{:descriptor.local_data.container_id}}">
					<div class="container-fluid">
						<div class="row-fluid">&nbsp;</div>
						<div class="row-fluid">
							<div id="placeholder_{{:descriptor.scrollers.organizationrequestlist.local_data.container_id}}"></div>
						</div>
					</div>
				</div>
			{{/if}}
		</div>
	</div><!-- /.row-fluid -->
</div><!-- /.container-fluid -->
</script>