<script id="profile_template" type="text/x-jsrender">
<span></span>
<div class="container-fluid" id="{{:descriptor.local_data.container_id}}">
	<div class="row">
		<div class="pull-right">
			{{if !~inModal}}
				{{if descriptor.operations ~descriptor=descriptor}}
					{{for descriptor.operations tmpl="operation" /}}
				{{/if}}
				<button type="button" class="btn btn-default" data-dismiss="modal" onclick="location.reload();">Отмена</button>
			{{/if}}
			<div>&nbsp;</div>
		</div><!-- /.pull-right -->
	</div><!-- /.row -->
	<div class="row-fluid">
		<div class="container-fluid">
			<div class="form-horizontal">
				{{if descriptor.fields ~fields=~utilities.objectToArray(descriptor.fields) ~descriptor=descriptor}}
					{{for ~fields}}
						{{if !(access && access == "hidden") }}
							<div class="form-group" name="field_{{:id}}">
								<label for="field_{{:id}}_value" class="col-sm-2 control-label">{{:name}}{{if ~utilities.isFieldRequired(#data) == true && access == "edit"}}<span class="text-danger">*<span>{{/if}}</label>
								<div class="col-sm-8">
									{{if id == "id"}}
										{{include tmpl = access + "_entity_field_label" /}}
									{{else id == "active"}}
										{{include tmpl = access + "_entity_field_bool" /}}
									{{else id == "name"}}
										{{include tmpl = access + "_entity_field_text" /}}
									{{else id == "email"}}
										{{include tmpl = access + "_entity_field_text" /}}
									{{else id == "phone"}}
										{{include tmpl = access + "_entity_field_text" /}}
									{{else id == "user_role"}}
										{{include tmpl = access + "_entity_field_link" /}}
									{{else id == "password"}}
										{{include tmpl = access + "_entity_field_password" /}}
										<!--<button type="button" class="btn btn-default" data-toggle="modal" data-target="#recoverModal">Напомнить пароль</button>
										<button type="button" class="btn btn-default" data-toggle="modal" data-target="#changeModal">Изменить пароль</button>-->
									{{/if}}
								</div>
							</div>
						{{/if}}
					{{/for}}
				{{/if}}
			</div>
		</div>
	</div><!-- /.row-fluid -->
</div><!-- /.container-fluid -->
</script>