<script id="profile_template" type="text/x-jsrender">
<span></span>
<div class="container-fluid" id="{{:descriptor.local_data.container_id}}">
	<div class="row">
		<div class="pull-right">
			{{if !~inModal}}
				{{if descriptor.operations ~descriptor=descriptor}}
					{{for descriptor.operations tmpl="operation" /}}
				{{/if}}
				<button type="button" class="btn btn-default" data-dismiss="modal" onclick="location.reload();">Отмена</button>
			{{/if}}
			<div>&nbsp;</div>
		</div><!-- /.pull-right -->
	</div><!-- /.row -->
	<div class="row-fluid">
		<div class="container-fluid">
			<div class="form-horizontal">
				{{if descriptor.fields ~fields=~utilities.objectToArray(descriptor.fields)}}
					{{for ~fields ~descriptor=descriptor}}
						<div class="form-group" name="field_{{:id}}">
							<label for="field_{{:id}}_value" class="col-sm-2 control-label">{{:name}}</label>
							<div class="col-sm-8">
								{{if id == "id"}}
									{{include tmpl = ~descriptor.actionName + "_entity_field_label" /}}
								{{else id == "active"}}
									{{include tmpl = "show_entity_field_bool" /}}
								{{else id == "name"}}
									{{include tmpl = ~descriptor.actionName + "_entity_field_text" /}}
								{{else id == "email"}}
									{{include tmpl = ~descriptor.actionName + "_entity_field_label" /}}
								{{else id == "phone"}}
									{{include tmpl = ~descriptor.actionName + "_entity_field_text" /}}
								{{else id == "user_role"}}
									{{include tmpl = ~descriptor.actionName + "_entity_field_label" /}}
								{{else id == "password"}}
									{{include tmpl = ~descriptor.actionName + "_entity_field_password" /}}
									<!--<button type="button" class="btn btn-default" data-toggle="modal" data-target="#recoverModal">Напомнить пароль</button>
									<button type="button" class="btn btn-default" data-toggle="modal" data-target="#changeModal">Изменить пароль</button>-->
								{{/if}}
							</div>
						</div>
					{{/for}}
				{{/if}}
			</div>
		</div>
	</div><!-- /.row-fluid -->
</div><!-- /.container-fluid -->
</script>