<div id="container_modals"></div>

<script id="modal_template" type="text/x-jsrender">
<span></span>
<!--<br>templates\modal_template-->
<div class="modal" id="{{:modal_container_id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel_{{:modal_container_id}}" data-backdrop="static">
	<div class="modal-dialog modal-lg" {{if (descriptor.type=='scroller' || (descriptor.scrollers && ~utilities.getOjectKeysCount(descriptor.scrollers) > 0)) }}style="width: 95%" {{/if}} role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel_{{:descriptor.local_data.udid}}">{{:descriptor.title}}</h4>
			</div>
			<div class="modal-body">
				<div class="container-fluid">
					<div class="row">
						<div class="pull-right">
							{{if descriptor.type == "entity"}}
								{{if descriptor.operations ~descriptor=descriptor}}
									{{for descriptor.operations tmpl="operation" /}}
								{{/if}}
								<button type="button" class="btn btn-default" data-dismiss="modal" onclick="hideModal('{{:modal_container_id}}');">Отмена</button>
							{{else}}
								<button type="button" class="btn btn-primary" onclick="linkSelectedRows('{{:descriptor.local_data.container_id}}');">Выбрать</button>
								<button type="button" class="btn btn-default" data-dismiss="modal" onclick="hideModal('{{:modal_container_id}}');">Отмена</button>
							{{/if}}
							<div>&nbsp;</div>
						</div><!-- /.pull-right -->
					</div><!-- /.row -->
					<div class="row">
						{{include tmpl="#"+tmplName ~inModal=1/}}
					</div><!-- /.row -->
				</div><!-- /.container-fluid -->
			</div>
			<div class="modal-footer"></div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
</script>

<script id="scroller_template" type="text/x-jsrender">
<span></span>
<div class="container-fluid">
	<div class="row">
		<div class="panel panel-default" id="{{:descriptor.local_data.container_id}}">
			<div class="panel-heading stat-scroller-header"{{if !(descriptor.notCollapsible == "1")}} data-toggle="collapse" data-target="#{{:descriptor.local_data.container_id}}CollapseDiv{{/if}}">
				{{:descriptor.title}}
				{{if !(descriptor.notCollapsible == "1")}}<span class="pull-right "><button type="button" class="btn btn-default btn-xs"><i class="glyphicon glyphicon-minus"></i></button></span>{{/if}}
			</div><!-- /.panel-heading -->
			<!--<div class="panel-body"> не используется с таблицей в panel-->
			{{if !(descriptor.notCollapsible == "1")}}<div id="{{:descriptor.local_data.container_id}}CollapseDiv" class="collapse in">{{/if}}<!---->
			<!--<div class="panel-body">-->
				<input hidden="" id="page" value="{{:descriptor.filter_values.page}}">
				<input hidden="" id="sort" value="{{:descriptor.filter_values.sort}}">
				<input hidden="" id="order" value="{{:descriptor.filter_values.order}}">
				<input hidden="" id="page_size" value="{{:descriptor.filter_values.page_size}}">
				
				{{if descriptor.columns ~columns=~utilities.objectToArray(descriptor.columns) ~descriptor=descriptor}}
				<div class="table-responsive"> 
					<table id="{{:descriptor.local_data.container_id}}" class="table table-striped table-bordered table-hover table-condensed">
						<thead>
							{{if descriptor.group_operations.length > 0 || descriptor.common_operations > 0 ~descriptor=descriptor}}
								<!-- строка общих операций -->
								<tr>
									<td colspan="{{:~columns.length+2}}">
										<div class="pull-right" role="group" aria-label="...">&nbsp;
											{{for descriptor.common_operations tmpl="common_operation" /}}
										
											{{for descriptor.group_operations}}
												<div class="btn-group"><button type="button" class="btn btn-xs dropdown-toggle" data-toggle="dropdown">С выбранными<span class="caret"></span></button><ul class="dropdown-menu">{{include tmpl="button_group_delete"/}}</ul></div>
											{{/for}}
										</div><!-- /.btn-group -->
									</td>
								</tr>
							{{/if}}
							<!-- строка заголовков -->
							<tr>
								{{if descriptor.group_operations.length > 0}}<th>{{if ~descriptor.local_data.select_style == "radio"}}{{else}}<input type="checkbox" name="{{:~descriptor.local_data.container_id}}" class="toggle-all"/>{{/if}}</th>{{/if}}
								{{for ~columns}}
									<th{{if hideble}} class="hidden-xs hidden-sm hidden-md"{{/if}}>
										{{if sortable}}
											<span onclick="change_sort('{{:~descriptor.local_data.container_id}}', '{{:id}}');"><u>{{:name}}</u></span>
											{{if id === ~descriptor.filter_values.sort}}
												<button type="button" class="btn btn-default btn-xs" aria-label="{{:name}}" name="{{:id}}" onclick="change_sort('{{:~descriptor.local_data.container_id}}', '{{:id}}');">
												{{if ~descriptor.filter_values.order === "DESC"}}
													<span class="glyphicon glyphicon-sort-by-attributes-alt" aria-hidden="true"></span>
												{{else}}
													<span class="glyphicon glyphicon-sort-by-attributes" aria-hidden="true"></span>
												{{/if}}
												</button>
											{{/if}}
										{{else}}
											{{:name}}
										{{/if}}
									</th>
								{{/for}}
							</tr>
						</thead>
						<tbody>
							{{if descriptor.filter_operations && descriptor.filter_operations.length>0}}
								<!-- строка фильтров -->
								<tr>
									{{if descriptor.group_operations.length > 0}}<td class="stat-row-checkbox-td"></td>{{/if}}
									{{for ~columns}}
										<td class="{{if hideble}}hidden-xs hidden-sm hidden-md {{/if}}{{if id == "id"}}stat-id-td{{else id == "active"}}stat-active-td{{else id == "operations"}}stat-operations-td{{/if}}">
											{{if filter}} 
												{{if filter==="text"}} <input type="text" name="filter_{{:id}}" value="{{:filter_value}}" class="form-control input-sm"/>
												{{else filter==="number"}} <input type="number" name="filter_{{:id}}" value="{{:filter_value}}"{{if id == "id"}} class="form-control input-sm stat-id-input-field"{{/if}} min="0"/>
												{{else filter==="email"}} <input type="email" name="filter_{{:id}}" value="{{:filter_value}}" class="form-control input-sm"/>
												{{else filter==="select"}}
													{{if filter_values.length>10}}<div class="input-group-sm">{{/if}}
														<select name="filter_{{if filter_id }}{{:filter_id}}{{else}}{{:id}}{{/if}}" class="form-control input-sm {{if filter_values.length>2}}extended{{/if}}" style="width:100%;">
															<option value="*" {{if filter_value===""}} selected="selected"{{/if}}></option>
															{{if nullSubstitute && nullSubstitute != "undefined"}}<option value="**" {{if filter_value=='**'}} selected="selected"{{/if}}>{{:nullSubstitute}}</option>{{/if}}
															{{if style === "id"}}
																{{for filter_values ~filter_value=filter_value}}<option value="{{:id}}" {{if id==~filter_value}}selected="selected"{{/if}}>{{:name}}</option>{{/for}}
															{{else }}
																{{for filter_values ~filter_value=filter_value}}<option value="{{:#data}}" {{if #data==~filter_value}}selected="selected"{{/if}}>{{:#data}}</option>{{/for}}
															{{/if}}
														</select>
													{{if filter_values.length>2}}</div>{{/if}}
												{{else filter==="bool"}}
													<select name="filter_{{:id}}" class="form-control input-sm">
														<option value="*" {{if filter_value == "*" || filter_value == ""}} selected="selected"{{/if}}></option>
														<option value="1" {{if filter_value == "1"}} selected="selected"{{/if}}>Да</option>
														<option value="0" {{if filter_value == "0"}} selected="selected"{{/if}}>Нет</option>
													</select>
												{{/if}}
											{{else id==="operations"}}
												{{for ~descriptor.filter_operations tmpl="filter_operation" /}}
											{{/if}}
										</td>
									{{/for}}
								</tr>
							{{/if}}
							
							<!-- строки с данными -->
							<!-- добавленные строки -->
							{{if ~descriptor.local_data.added_items && ~descriptor.local_data.added_items.length>0  }}
								{{for ~descriptor.local_data.added_items}}
									<tr class="odd gradeX success{{if ~descriptor.local_data.status=='actual' && fields.id.value != -1}} status-actual{{/if}} {{:fields.id.value}}">
										{{include tmpl=~descriptor.controllerName+"_row" /}}
									</tr>
								{{/for}}
							{{/if}}	
							<!-- удаленные строки -->
							{{if ~descriptor.local_data.deleted_items && ~descriptor.local_data.deleted_items.length>0  }}
								{{for ~descriptor.local_data.deleted_items }}
									<tr class="odd gradeX danger">
										{{include tmpl=~descriptor.controllerName+"_row" /}}
									</tr>
								{{/for}}
							{{/if}}	
							<!-- стандартные строки -->
							{{if ~descriptor.items && ~descriptor.items.length>0 }}
								{{for ~descriptor.items }}
									<tr class="odd gradeX {{if local_data.status=='edited'}}warning{{/if}}">
										{{include tmpl=~descriptor.controllerName+"_row" /}}
									</tr>
								{{/for}}
							{{else (!~descriptor.local_data.added_items || ~descriptor.local_data.added_items.length==0) && (!~descriptor.local_data.deleted_items || ~descriptor.local_data.deleted_items.length==0) }}	
								<!-- если данных нет -->
								<tr ><td colspan="{{if descriptor.group_operations.length > 0}}{{:~columns.length+2}}{{else}}{{:~columns.length+1}}{{/if}}"><p class="text-center"><?php echo $t->_('text_no_data'); ?></p></td></tr>
							{{/if}}
						</tbody>
					</table>
					</div>
				{{/if}}
				<!--</div> /.panel-body -->
				<div class="panel-footer">
					<!-- записей на странице -->
					<span class="pull-right"><?php echo $t->_('text_page_sizes'); ?>&nbsp;{{include tmpl="page_size" ~descriptor=descriptor /}}</span>
					{{for descriptor.pager ~descriptor=descriptor }}
						<nav>
							<ul class="pagination stat-pager">
								{{if ~descriptor.filter_values.page>1}}
									<li onClick="change_page('{{:~descriptor.local_data.container_id}}', {{:~descriptor.filter_values.page}}-1);"><a href="#" aria-label="pager_prev"><span aria-hidden="true">&laquo;</span></a></li>
								{{else}}
									<li class="disabled"><span aria-label="Previous"><span aria-hidden="true">&laquo;</span></span></li>
								{{/if}}
								<!-- выводим номера страниц -->
								{{:~utilities.getPagerHtml(~descriptor)}}
								{{if ~descriptor.filter_values.page<~descriptor.pager.total_pages}}
									<li onClick="change_page('{{:~descriptor.local_data.container_id}}', {{:~descriptor.filter_values.page}}+1);"><a href="#" aria-label="pager_next"><span aria-hidden="true">&raquo;</span></a></li>
								{{else}}
									<li class="disabled"><span aria-label="Next"><span aria-hidden="true">&raquo;</span></span></li>
								{{/if}}
							</ul>
						</nav>
					{{/for}}
				</div>
			{{if !(descriptor.notCollapsible == "1")}}</div>{{/if}} <!--/#{{:descriptor.local_data.container_id}}CollapseDiv -->
		</div><!-- /.panel -->
	</div><!-- /.row -->
</div><!-- /.container-fluid -->
</script>

<script type="text/javascript"><!--


function initScrollerScripts(container_id) {
	var container = containers[container_id];
	// если у скроллера есть общий чекбокс для всех, то настраиваем его переключение
	var toggleAll = container.jqobj.find("input.toggle-all:not(:has(.inited))");
	toggleAll.on('change', function() {
		//alert(containers[container_id].jqobj.find("tbody tr input[name^='row_scroller']").length);
		containers[container_id].jqobj.find("input[name^='row_scroller']").each(function(indx, element){
			$(this).prop("checked", $("#" + container_id + " input.toggle-all[name='" + container_id + "']").prop('checked'));
		});
	});
	toggleAll.addClass("inited");
	
	// если скроллер сворачиваемый, то добавляем смену индикатора развернутости в заголовке скроллера
	container.jqobj.find(".panel-heading[data-toggle='collapse']").each(function(indx, element) {
		$(this).on('click', function(e) {
			var icon = $(this).find('i');
			if(icon.hasClass('glyphicon-minus')) icon.removeClass('glyphicon-minus').addClass('glyphicon-plus');
			else icon.removeClass('glyphicon-plus').addClass('glyphicon-minus');
		});
	});
	
	// если скроллер открыт на странице, то инициализируем кнопки удаления, с вопросом о подтверждении
	/*if(!container.parent_container_id) {
		container.jqobj.find("button[data-toggle='popover']").each(function(indx, element) {
			var btn = $(this);
			// определяем, является ли это кнопка удаления
			var rb = btn.find('span.glyphicon-remove');
			if(rb.length == 1) {
				var options = {
					placement: 'top',
					title: 'Вы уверены, что хотите удалить запись?',
					content: function() {
						var html = '<button type="button" class="btn btn-xs" aria-label="Да" name="yes" onclick="">Да</button><button type="button" class="btn btn-xs" aria-label="Нет" name="no" onclick="">Нет</button>';
						return html;
					},
				}
				var pp = btn.popover(options);
				pp.find('div.popover-content').each(function(indx, element) {
					($this).html('<button type="button" class="btn btn-xs" aria-label="Да" name="yes" onclick="">Да</button><button type="button" class="btn btn-xs" aria-label="Нет" name="no" onclick="">Нет</button>');
				});
			}
			btn.on('click', function() {$(this).popover('show');});
		});
	}*/
	
	// для полей input строки фильтра добавляем применение фильтрации по Enter
	container.jqobj.find("input[name^='filter_']:not(:has(.inited))").each(function(indx, element) {
		$(this).focusin(function(){
			$(this).bind('keypress', function(e) {
				if(e.keyCode==13){
					apply_filter(container_id);
				}
			});
		}).focusout(function(){
			$(this).unbind('keypress', false);
		}).addClass("inited");
	});
	
	// если есть строки в добавленных, которые добавлены с сохранением на сервер, то анимируем изменение цвета статуса success
	container.jqobj.find("tr.status-actual").each(function(indx, element) {
		var obj = $(this);
		setTimeout(function(){
            obj.removeClass('status-actual success');
		}, 2000);  
	});
	
	// улучшаем выпадающие списки
	if ($.fn.select2) {
		$.fn.select2.defaults.set( "theme", "bootstrap");
		$("select.extended").select2();
	}
}

/* Переход к просмотру строки
* @container_id - идентифкатор контейнера (скроллера), запись которого необходимо открыть на просмотр
* @id - id (eid) просматриваемой сущности (null, если создается новая сущность)
*/
function row_show(container_id, id) {
	// родительский контейнер (скроллер), элемент которого открываем
	var container = containers[container_id];
	var scroller = container.data;
	url = '/'+scroller.entity + '/show' + (id ? '?id=' + id : '');
	
	if(scroller.edit_style=="url") {
		//console.log("row_edit_entity=" + url);
		document.location = url;
	}
	else if(scroller.edit_style=="modal") {
		// если сущность открыта в другой модалке или на родительской форме, то сообщаем об этом
		if(entities[scroller.entity] && entities[scroller.entity][id]) {
			if(containers[entities[scroller.entity][id].local_data.container_id]) {
				// TODO. такие уведомлялки делать в виде Popup на кнопке, исчезающего через несколько секунд
				alert("Сущность уже открыта на редактирование в другой экранной форме. Завершите работу с диалогами и вернитесь к редактированию сущности");
				return;
			}
			// если сущность не сохранена на сервере или сущность сохранена на сервере, но она отредактирована / удалена локально
			if(entities[scroller.entity][id].fields.id.value == -1 || (entities[scroller.entity][id].fields.id.value != -1 && entities[scroller.entity][id].local_data.status != 'actual')) {
				// рисуем модалку
				var modal_container_id = renderModal(entities[scroller.entity][id], container);
				
				// показываем модалку
				showModal(modal_container_id);
				return;
			}
		}
		
		// запрашиваем с сервера более подробную информацию (всю сущность, а не только скроллерную запись)
		// при этом, если выполняется операция add, то будет запрошена информация пустой сущности
		$.ajax({
			url: url,
			dataType: 'json',
			method: 'get',
			beforeSend: function() {
					// показываем прогрессбар
			},
			complete: function() {
				// скрываем прогрессбар
			},			
			success: function(json) {
				if(!handleAjaxError(json.error)) {
					//console.log("С сервера получены полные данные сущности скроллера:");
					console.log(json);
					
					// сохраняем полученные данные
					var local_entity = saveFullServerEntity(json);
					//if(!id) local_entity.local_data.status = 'added';
					//local_entity.local_data.target_container_id = container.local_data.container_id;
					if(scroller.relationType) local_entity.local_data.relationType = scroller.relationType;
					
					// присваиваем идентификаторы скролерам, чтобы при выводе основных данных сущности оставить метки для их размещения
					initEntityScrollers(local_entity);
					
					// рисуем модалку
					var modal_container_id = renderModal(local_entity, container);
					
					// показываем модалку
					showModal(modal_container_id);
				}
			},
			error: function(xhr, ajaxOptions, thrownError) {
				console.log(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
				handleAjaxError({
					messages: [{
						title: 'Ошибка обмена данными',
						msg: 'Ошибка обработки запроса на стороне сервера. Обратитесь в службу поддержки',
					}],
				});
			}
		});
	}
	else {
		alert("Запрошен просмотр сущности с неизвестным scroller.edit_style");
	}
}

/* Переход к редактированию строки
* @container_id - идентифкатор контейнера (скроллера), запись которого необходимо открыть на редактирование
* @id - id (eid) редактируемой сущности (null, если создается новая сущность)
*/
function row_edit(container_id, id) {
	// родительский контейнер (скроллер), элемент которого открываем
	var container = containers[container_id];
	var scroller = container.data;
	url = '/'+scroller.entity + '/edit' + (id ? '?id=' + id : '');
	
	if(scroller.edit_style=="url") {
		//console.log("row_edit_entity=" + url);
		document.location = url;
	}
	else if(scroller.edit_style=="modal") {
		// если сущность открыта в другой модалке или на родительской форме, то сообщаем об этом
		if(entities[scroller.entity] && entities[scroller.entity][id]) {
			if(containers[entities[scroller.entity][id].local_data.container_id]) {
				// TODO. такие уведомлялки делать в виде Popup на кнопке, исчезающего через несколько секунд
				alert("Сущность уже открыта на редактирование в другой экранной форме. Завершите работу с диалогами и вернитесь к редактированию сущности");
				return;
			}
			// если сущность не сохранена на сервере или сущность сохранена на сервере, но она отредактирована / удалена локально
			if(entities[scroller.entity][id].fields.id.value == -1 || (entities[scroller.entity][id].fields.id.value != -1 && entities[scroller.entity][id].local_data.status != 'actual')) {
				// рисуем модалку
				var modal_container_id = renderModal(entities[scroller.entity][id], container);
				
				// показываем модалку
				showModal(modal_container_id);
				return;
			}
		}
		
		// запрашиваем с сервера более подробную информацию (всю сущность, а не только скроллерную запись)
		// при этом, если выполняется операция add, то будет запрошена информация пустой сущности
		$.ajax({
			url: url,
			dataType: 'json',
			method: 'get',
			beforeSend: function() {
					// показываем прогрессбар
			},
			complete: function() {
				// скрываем прогрессбар
			},			
			success: function(json) {
				if(!handleAjaxError(json.error)) {
					//console.log("С сервера получены полные данные сущности скроллера:");
					console.log(json);
					
					// сохраняем полученные данные
					var local_entity = saveFullServerEntity(json);
					//if(!id) local_entity.local_data.status = 'added';
					//local_entity.local_data.target_container_id = container.local_data.container_id;
					if(scroller.relationType) local_entity.local_data.relationType = scroller.relationType;
					
					// присваиваем идентификаторы скролерам, чтобы при выводе основных данных сущности оставить метки для их размещения
					initEntityScrollers(local_entity);
					
					// рисуем модалку
					var modal_container_id = renderModal(local_entity, container);
					
					// показываем модалку
					showModal(modal_container_id);
				}
			},
			error: function(xhr, ajaxOptions, thrownError) {
				console.log(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
				handleAjaxError({
					messages: [{
						title: 'Ошибка обмена данными',
						msg: 'Ошибка обработки запроса на стороне сервера. Обратитесь в службу поддержки',
					}],
				});
			}
		});
	}
	else {
		alert("Запрошено создание/редактирование сущности с неизвестным scroller.edit_style");
	}
}

/* Удаляет строку из скроллера/грида. Если скроллер отображается не в рамках сущности, то удаление строки выполняется с сервера
* @container_id - идентифкатор контейнера (скроллера), запись которого необходимо удалить
* @id - id удаляемой сущности
*/
function row_delete(container_id, id) {
	container = containers[container_id];
	// родительский скроллер/грид, с элементом которого работаем
	var scroller = containers[container_id].data;
	// описатель удаляемой сущности
	var entity = entities[scroller.entity][id];
	
	// удаляем с запросом, если этот скроллер открыт на отдельной странице или в ммодеальном окне,т.е. не предусмотрена кнопка "Сохранить" или "Применить"
	if((!container.parent_container_id)){// ||
		// отображается на форме сущности и отношение 'n' и сущность, т.е. сущности скроллера создаются только для текущей сущности
		//(container.parent_container_id && containers[container.parent_container_id].data.type == 'entity' && scroller.relationType == 'n')) {
		
		entityDelete(container_id, id).done(function (){
			deleteItemFromScroller(entity, scroller, {confirmFromServer:true});
			renderScroller(scroller);
		});
	}
	// помечаем удаленными в скроллере
	else {
		deleteItemFromScroller(entities[scroller.entity][id], scroller, {confirmFromServer:false})
		renderScroller(scroller);
	}
}

// Запрашивает и выводит отфильтрованные данные
function apply_filter(container_id) {
	var container = containers[container_id];
	var data = container.data;
	var udid = data.local_data.udid;
	var jqobj = container.jqobj;
	var rq = {};
	var controllerName = data.controllerName;
	
	url = '/'+controllerName+'/index';
	
	if(container.parent_container_id) {
		var parentData = containers[container.parent_container_id].data;
		if(parentData.type === 'entity') {
			rq.scrollerName = controllerName;
			rq.actionName = parentData.actionName;
			controllerName = parentData.controllerName;
			url = '/'+controllerName+'/filter';
		}
	}
	
	
	// собираем служебные поля фильтра скроллера
	var page = jqobj.find('#page').val();
	//url += 'page=' +  encodeURIComponent(page ? page : 1);
	rq.page = encodeURIComponent(page ? page : 1);
	
	var sort = jqobj.find('#sort').val();
	//if (sort) url += '&sort=' + encodeURIComponent(sort);
	if (sort) rq.sort = encodeURIComponent(sort);
	
	var order = jqobj.find('#order').val();
	//if (order) url += '&order=' + encodeURIComponent(order);
	if (order) rq.order = encodeURIComponent(order);
	
	var page_size = jqobj.find("select[name='page_sizes']").val();
	//if (page_size) url += '&page_size=' + encodeURIComponent(page_size);
	if (page_size) rq.page_size = encodeURIComponent(page_size);
	
	// пробегаемся по столбцам, чтобы собрать данные фильтров в столбцах данных
	var tr_offs = (data.group_operations && data.group_operations.length > 0) ? 2 : 1;
	var columns = jqobj.find("table tr:eq("+tr_offs+") td");
	var columns_length = columns.length;
	for(var i=0; i<columns_length; i++){
		var field = columns.eq(i).find("input[name^='filter_']").filter("[type='text'], [type='number'], [type='email']");
		if(field.val()) {//url += '&'+field.attr("name")+'=' + encodeURIComponent(field.val());
			rq[field.attr("name")] = encodeURIComponent(field.val());
			//console.log('filter = ' + rq[field.attr("name")]);
		}
		else {
			field = columns.eq(i).find("select[name^='filter_']");
			if(field.val() && field.val() == "**") //url += '&'+field.attr("name")+'=' + encodeURIComponent(field.val());
				rq[field.attr("name")] = encodeURIComponent(field.val());
			else if(field.val() && field.val() != "*") //url += '&'+field.attr("name")+'=' + encodeURIComponent(field.val());
				rq[field.attr("name")] = encodeURIComponent(field.val());
			else {
				// TODO: checkbox и пр.
			}
		}
	}
	
	// доп. фильтры, используются при фильтрации скроллеров в сущностях для передачи id сущности
	if(data.add_filter) {
		rq.add_filter = {};
		for (var key in data.add_filter) rq.add_filter[key] = data.add_filter[key];
	}
	// исключение айдишников
	if(data.filter_values.exclude_ids) {
		rq.exclude_ids = data.filter_values.exclude_ids;
	}
	// статичные фильтры
	if (typeof static_filter_values !== "undefined") {
		for (var key in static_filter_values) rq[key] = static_filter_values[key];
	}
	
	console.log(url);
	$.ajax({
		url: url,
		data: rq,
		dataType: 'json',
		//dataType: 'html',
		method: 'post',
		beforeSend: function() {
				// показываем прогрессбар
		},
		complete: function() {
			// скрываем прогрессбар
		},			
		success: (function(json) {
			if(!handleAjaxError(json.error)) {
				// используется замкание и bind, в свойстве this хранится container скроллера, как контекст
				console.log(json);
				
				// сохраняем способ редактирования скроллера в данном контейнере перед копирование
				var add_style = this.data.add_style;
				
				copyDescriptor(json, this.data);
				delete json;
				
				// восстанавливаем способ редактирования после копирования
				this.data.add_style = add_style;
				
				// TODO. Необходимо удалить из added_items записи, которые находятся в полученном items, т.к. это значит, что кто-то уже добавил эту запись
				var isFound = false;
				var len;
				if(this.data.local_data.added_items) {
					len = this.data.local_data.added_items.length;
					for(var i = 0; i<len; i++) {
						var item = this.data.local_data.added_items[i];
						var itemsLen = this.data.items.length;
						for(var j = 0; j<itemsLen; j++) {
							if(item.fields.id.value == this.data.items[j].fields.id.value) {
								this.data.local_data.added_items.items.splice(i,1);
								isFound = true;
								break;
							}
						}
					}
				}
				// TODO. Необходимо удалить из items записи, которые находятся в deleted_items
				if(this.data.local_data.deleted_items && !isFound) {
					len = data.items.length;
					for(var i = 0; i<len; i++) {
						var item = this.data.local_data.deleted_items[i];
						var itemsLen = this.data.items.length;
						for(var j = 0; j<itemsLen; j++) {
							if(item.fields.id.value == this.data.items[j].fields.id.value) {
								this.data.items.splice(i,1);
								break;
							}
						}
					}
				}
				
				// сохраняем в виде локальных сущностей записи скроллера
				saveScrollerItems(this.data);
				
				renderScroller(this.data);
			}
		}).bind(container),
		error: function(xhr, ajaxOptions, thrownError) {
			console.log(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
			handleAjaxError({
				messages: [{
					title: 'Ошибка обмена данными',
					msg: 'Ошибка обработки запроса на стороне сервера. Обратитесь в службу поддержки',
				}],
			});
		}
	});
}

// клик по номеру страницы
function change_page(container_id, p){
	console.log('p='+p);
	containers[container_id].jqobj.find('#page').val(p);
	console.log('page='+containers[container_id].jqobj.find('#page').val());
	apply_filter(container_id);
}

// клик по сортировке колонки
function change_sort(container_id, id){
	var order = containers[container_id].jqobj.find("#order");
	var sort = containers[container_id].jqobj.find("#sort");
	if(sort.val()==id) order.val() == "DESC" ? order.val("ASC") : order.val("DESC");
	else sort.val(id);
	apply_filter(container_id);
}

// выбор количества строк на странице
function change_page_size(container_id){
	containers[container_id].jqobj.find("#page_size").val(containers[container_id].jqobj.find("select[name='page_sizes']").val());
	apply_filter(container_id);
}

// Очистка бизнес-полей фильтра, запрашивает и выводит отфильтрованные данные
function clear_filter(container_id) {
	var data = containers[container_id].data;
	var tr_offs = ((data.group_operations && data.group_operations.length > 0) ? 2 : 1);
	var columns = containers[container_id].jqobj.find("#" + createUDID(data) + " table tr:eq("+tr_offs+") td");
	for(var i=0;i<columns.length;i++){
		columns.eq(i).find("input[name^='filter_'], select[name^='filter_']").each(function(){
			$(this).val("");
		});
		// TODO: checkbox и пр.
	}
	apply_filter(container_id);
}
//--></script>