<script type="text/javascript"> 

(function (app) {
	"use strict";
	
	var currLanguage = '<?php echo $t->language; ?>';
	
	var messages = {
		<?php echo $t->language; ?>: <?php echo json_encode($t->messages); ?>,
	};
	
	var obj = {};
	
	obj._ = function(code, params) {
		if((!code || typeof code != 'string') && (params !== null && typeof params !== 'object')) return '<Модуль Переводчик. В функцию перевода переданы неверные параметры>';
		
		var result = code;
		if(messages[currLanguage][code]) {
			result = messages[currLanguage][code];
			for (var key in params) {
				var value = params[key];
				result = result.replace(new RegExp('{' + key + '}', 'g') , value);
			}
		}
		return result;
	};
	
	obj.addTranslation = function(translation, language) {
		for (var key in translation) {
			if(!messages[language]) messages[language] = {};
			messages[language][key] = translation[key];
		}
	};
	
	obj.messages = messages;
	
	app.t = obj;
	
}(app));
</script> 
