<!--<br>layouts\menu-->
<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Навигация</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/"><?php echo $controller->t->_("text_site_short_name"); ?></a>
		</div>
		
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse navbar-left" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Содержимое <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<?php if($controller->acl->isAllowed($controller->userData['role_id'], 'organizationlist', 'index')) { ?><li><a href="/organizationlist">Организации</a></li><?php } ?>
						<!--<li role="separator" class="divider"></li>-->
						
						<?php if($controller->acl->isAllowed($controller->userData['role_id'], 'newslist', 'index')) { ?><li><a href="/newslist">Новости</a></li><?php } ?>
					</ul>
				</li>
				<li>
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Настройки сайта <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<?php if($controller->acl->isAllowed($controller->userData['role_id'], 'userlist', 'index')) { ?><li><a href="/userlist">Пользователи</a></li><?php } ?>
						<?php if($controller->acl->isAllowed($controller->userData['role_id'], 'userrolelist', 'index')) { ?><li><a href="/userrolelist">Роли пользователей</a></li><?php } ?>
						<?php if($controller->acl->isAllowed($controller->userData['role_id'], 'resourcelist', 'index')) { ?><li><a href="/resourcelist">Ресурсы сайта</a></li><?php } ?>
						<?php if($controller->acl->isAllowed($controller->userData['role_id'], 'settinglist', 'index')) { ?><li><a href="/settinglist">Настройки (параметры)</a></li><?php } ?>
						<?php if($controller->acl->isAllowed($controller->userData['role_id'], 'streettypelist', 'index')) { ?><li><a href="/streettypelist">Типы улиц</a></li><?php } ?>
						<?php if($controller->acl->isAllowed($controller->userData['role_id'], 'expensetypelist', 'index')) { ?><li><a href="/expensetypelist">Типы расходов</a></li><?php } ?>
						<?php if($controller->acl->isAllowed($controller->userData['role_id'], 'regionlist', 'index')) { ?><li><a href="/regionlist">Регионы</a></li><?php } ?>
						<?php if($controller->acl->isAllowed($controller->userData['role_id'], 'expensestatuslist', 'index')) { ?><li><a href="/expensestatuslist">Статусы расходов</a></li><?php } ?>
					</ul>
				</li>
				
			</ul>
		</div><!-- /.navbar-collapse -->
		<ul class="nav navbar-nav navbar-right">
			<li>
				<p class="navbar-text"><?php if(isset($controller->userData['name'])) { echo $controller->userData['name']; ?> (<a href="/session/end" class="navbar-link">выход</a>)<?php }else echo "Гость"; ?></p>
			</li>
		</ul>
	</div><!-- /.container-fluid -->
</nav>
