<!--<div class="row">
	<div class="col-lg-12"><button type="button" class="btn btn-default" name="" onclick="sendEmail();"><span class="glyphicon glyphicon-email">Отправить</span></button></div>
</div> /.row -->
<?php if(count($orgs) > 0) { ?>
	<div class="row">
		<div class="col-lg-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h1 class="panel-title"><?php echo $controller->t->_("index_index_my_organizations"); ?></h1>
				</div>
				<div class="panel-body">
					<div class="row">
						<?php foreach($orgs as $org) { ?>
							<div class="col-lg-2">
								<a href="/organization/index?id=<?php echo $org["id"]; ?>" class="thumbnail">
									<?php if($org["img"] != "") { ?>
										<img src="/<?php echo $org["img"]; ?>" alt="..." >
									<?php } else { ?>
										<img src="/no_image.jpg" alt="Нет изображения" >
									<?php } ?>
									<p class="text-center h4"><?php echo $org["name"]; ?></p>
								</a>
							</div>
						<?php } ?>
					</div><!-- /.row -->
				</div>
			</div>
		</div>
	</div><!-- /.row -->
<?php } ?>
<?php //var_dump( $user); ?>
<?php //var_dump( $orgs); ?>


<script type="text/javascript"><!--

function sendEmail() {
	$.ajax({
		url: '/index/sendemail',
		dataType: 'json',
		method: 'get',
		beforeSend: function() {
				// показываем прогрессбар
		},
		complete: function() {
			// скрываем прогрессбар
		},			
		success: function(json) {
			console.log(json);
			handleAjaxSuccess(json.success)
			if(!handleAjaxError(json.error)) {
				//if(json.success.redirect) document.location = json.success.redirect;
			}
			
		},
		error: function(xhr, ajaxOptions, thrownError) {
			console.log(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
			handleAjaxError({
				messages: [{
					title: 'Ошибка обмена данными',
					msg: 'Ошибка обработки запроса на стороне сервера. Обратитесь в службу поддержки',
				}],
			});
		}
	});
}


//--></script>

