<!--<div class="row">
	<div class="col-lg-12"><button type="button" class="btn btn-default" name="" onclick="sendEmail();"><span class="glyphicon glyphicon-email">Отправить</span></button></div>
</div> /.row -->
<?php if(count($orgs) > 0) { ?>
	<div class="row">
		<div class="col-lg-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h1 class="panel-title"><?php echo $controller->t->_("index_index_my_organizations"); ?></h1>
				</div>
				<div class="panel-body">
					<div class="row">
						<?php foreach($orgs as $org) { ?>
							<div class="col-lg-2">
								<div class="thumbnail">
									<a href="/organization/index?id=<?php echo $org["id"]; ?>">
										<?php if(isset($org["img"]) && $org["img"] != '') { ?>
											<img src="/<?php echo $org["img"]; ?>" alt="..." >
										<?php } else { ?>
											<img src="/no_image.jpg" alt="Нет изображения" >
										<?php } ?>
										<p class="text-center h4"><?php echo $org["name"]; ?></p>
									</a>
									<?php if(isset($org['organizationRequestCount'])) { ?>
										<p class="text-center">
											<button type="button" class="btn btn-default" aria-label="Left Align" onClick="document.location = '/organization?id=<?php echo $org["id"]; ?>&selected_tab=organizationrequestlist&filter_status=<?php echo $controller->config["application"]["requestStatus"]["newStatusID"]; ?>';" title="<?php if($org['organizationRequestCount'] && $org['organizationRequestCount'] > 0) { ?>Имеются не обработанных вопросы от граждан<?php } else { ?>Не обработанных вопросов от граждан нет<?php } ?>">
												<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <span class="label <?php if($org['organizationRequestCount'] > 0) { ?>label-danger<?php } else { ?>label-success<?php } ?>"><?php echo $org['organizationRequestCount']; ?></span>
											</button>
										</p>
									<?php } ?>
								</div>
							</div>
						<?php } ?>
					</div><!-- /.row -->
				</div>
			</div>
		</div>
	</div><!-- /.row -->
<?php } ?>
<?php //var_dump( $user); ?>
<?php //var_dump( $orgs); ?>
<?php //var_dump( $dbg); ?>
<?php //echo $dbg; ?>


<script type="text/javascript"><!--

var orgs = <?php echo json_encode($orgs); ?>;

document.addEventListener("DOMContentLoaded", function(event) { 
 // console.log(orgs);
});

function sendEmail() {
	$.ajax({
		url: '/index/sendemail',
		dataType: 'json',
		method: 'get',
		beforeSend: function() {
				// показываем прогрессбар
		},
		complete: function() {
			// скрываем прогрессбар
		},			
		success: function(json) {
			console.log(json);
			handleAjaxSuccess(json.success)
			if(!handleAjaxError(json.error)) {
				//if(json.success.redirect) document.location = json.success.redirect;
			}
			
		},
		error: function(xhr, ajaxOptions, thrownError) {
			console.log(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
			handleAjaxError({
				messages: [{
					title: 'Ошибка обмена данными',
					msg: 'Ошибка обработки запроса на стороне сервера. Обратитесь в службу поддержки',
				}],
			});
		}
	});
}


//--></script>

