<div class="row text-center">
	<div class="col-lg-offset-3 col-lg-6">
		<h1 class="page-header text-primary"><?php echo $t->_("text_site_full_name"); ?><br>
		<small class=""><?php echo $t->_("text_site_full_name_federal_project"); ?></small></h1>
	</div>
</div><!-- /.row-fluid -->
<div class="row">
	<div class="col-lg-offset-4 col-lg-4">
		<div class="form-signin" id="loginForm">
			<h2 class="form-signin-heading text-center"><?php echo $t->_("text_login_authorization"); ?></h2>
			<div class="input-group">
				<span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
				<input type="text" id="login" class="form-control" placeholder="<?php echo $t->_("text_login_login_placeholder"); ?>" autofocus="">
			</div>
			<br/>
			<div class="input-group">
				<span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
				<input id="password" type="password" class="form-control" name="password" value="" required="" placeholder="<?php echo $t->_("text_login_password_placeholder"); ?>">                                        
			</div>
			<br/>
			<div class="row"><div class="col-lg-12 text-right"><a href="#" data-toggle="modal" data-target="#recoverModal"><?php echo $t->_("button_password_recover"); ?></a></div></div>
			<br/>
			<!--<div class="checkbox">
				<label>
					<input type="checkbox" value="remember-me"> Запомнить меня
				</label>
			</div>-->
			<button type="button" class="btn btn-lg btn-primary btn-block" onclick="backendLogin();"><?php echo $t->_("button_enter"); ?></button>
		</div>
	</div>
</div><!-- /.row -->

<!-- Модальные окна -->
<div class="modal fade" id="recoverModal" tabindex="-1" role="dialog" aria-labelledby="recoverModalHeader" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="recoverModalHeader"><?php echo $t->_("text_password_recover_title"); ?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo $t->_("text_password_recover_annotation"); ?></p>
				<div class="input-group">
					<span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
					<input type="text" id="recoverLogin" class="form-control" placeholder="Логин" required>
				</div>
				<div><p id="recoverError" class="text-danger"></p></div>
				<div><p id="recoverSuccess" class="text-success"></p></div>
				<div>&nbsp;</div>
				<!--<button class="btn btn-lg btn-primary btn-block" type="submit" formmethod="get" formaction="/session/start">Войти</button>
				<button type="button" class="btn btn-primary btn-block" onclick="sendPassword();"><?php echo $t->_("button_send"); ?></button>-->
			</div>
			<div class="modal-footer">
				<!--<button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>-->
			</div>
		</div>
	</div>
</div>

<script type="text/javascript"><!--

function sendPassword() {
	var modal = $("#recoverModal");
	var loginJQ = modal.find('#login');
	var login = loginJQ.val();
	$('#loginSuccess').text('');
	$('#loginError').text('');
	loginJQ.parent().removeClass("has-error");
	
	if(!login) {
		loginJQ.parent().addClass("has-error");
		$('#loginError').text('Вы не указали логин');
		return;
	}
	if(login.indexOf('@') == -1) {
		loginJQ.parent().addClass("has-error");
		$('#loginError').text('Неверный адрес логин');
		return;
	}
	
	$('#loginError').text('');
	loginJQ.parent().removeClass("has-error");
	
	$.ajax({
		url: '/user/sendpassword?login=' + encodeURIComponent(login),
		dataType: 'json',
		method: 'get',
		beforeSend: function() {
				// показываем прогрессбар
		},
		complete: function() {
			// скрываем прогрессбар
		},			
		success: function(json) {
			console.log(json);
			handleAjaxSuccess(json.success)
			if(!handleAjaxError(json.error)) {
				if(json.success.redirect) document.location = json.success.redirect;
				//if(json.success && json.success.messages.length>0) $('#loginSuccess').text(json.success.messages[0].msg);
			}
		},
		error: function(xhr, ajaxOptions, thrownError) {
			console.log(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
			handleAjaxError({
				messages: [{
					title: 'Ошибка обмена данными',
					msg: 'Ошибка обработки запроса на стороне сервера. Обратитесь в службу поддержки',
				}],
			});
		}
	});
}

function backendLogin() {
	var url = '/session/start?';
	//var modal = $("#logonModal");
	var modal = $(".form-signin");
	
	var phone = modal.find('#phone').val();
	if (phone) url += 'phone=' + encodeURIComponent(phone);
	var login = modal.find('#login').val();
	if (login) url += (phone ? '&' : '') +'&login=' + encodeURIComponent(login);
	var password = modal.find('#password').val();
	password = sha1(password);
	if (password) url += '&password=' + encodeURIComponent(password);
	
	console.log(url);
	
	$.ajax({
		url: url,
		dataType: 'json',
		method: 'get',
		beforeSend: function() {
				// показываем прогрессбар
		},
		complete: function() {
			// скрываем прогрессбар
		},			
		success: function(json) {
			console.log(json);
			handleAjaxSuccess(json.success)
			if(!handleAjaxError(json.error)) {
				if(json.success.redirect) document.location = json.success.redirect;
			}
			
		},
		error: function(xhr, ajaxOptions, thrownError) {
			console.log(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
			handleAjaxError({
				messages: [{
					title: 'Ошибка обмена данными',
					msg: 'Ошибка обработки запроса на стороне сервера. Обратитесь в службу поддержки',
				}],
			});
		}
	});
}


//--></script>

