<div class="row-fluid text-center">
	<div class="row">
		<div class="col-lg-offset-3 col-lg-6">
			<h1 class="page-header"><?php if(isset($page_header)) echo $page_header; ?></h1>
		</div>
	</div><!-- /.row-fluid -->
<div class="row">
	<div class="col-lg-offset-4 col-lg-4">
		<div class="form-signin">
			<h2 class="form-signin-heading text-center">Авторизация</h2>
			<div class="input-group">
				<span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
				<input type="email" id="email" class="form-control" placeholder="Email" autofocus="">
			</div>
			<div class="row"><div class="col-lg-12 text-center">ИЛИ</div></div>
			<div class="input-group">
					<span class="input-group-addon"><i class="glyphicon glyphicon-phone-alt"></i></span>
					<input id="phone" type="tel" class="form-control" name="phone" value="" placeholder="Телефон" pattern="[0-9]+" maxlength="12">                                        
			</div>
			<div class="row"><div class="col-lg-12 text-center">&nbsp;</div></div>
			<div class="input-group">
					<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
					<input id="password" type="password" class="form-control" name="password" value="" required="" placeholder="Пароль">                                        
			</div>
			<div class="checkbox">
				<label>
					<input type="checkbox" value="remember-me"> Запомнить меня
				</label>
			</div>
			<button type="button" class="btn btn-lg btn-primary btn-block" onclick="backendLogin();">Войти</button>
		</div>
	</div>
</div><!-- /.row -->
<script type="text/javascript"><!--

function backendLogin() {
	var url = '/session/start?';
	//var modal = $("#logonModal");
	var modal = $(".form-signin");
	
	var phone = modal.find('#phone').val();
	if (phone) url += 'phone=' + encodeURIComponent(phone);
	var email = modal.find('#email').val();
	if (email) url += (phone ? '&' : '') +'&email=' + encodeURIComponent(email);
	var password = modal.find('#password').val();
	password = sha1(password);
	if (password) url += '&password=' + encodeURIComponent(password);
	
	console.log(url);
	
	$.ajax({
		url: url,
		dataType: 'json',
		method: 'get',
		beforeSend: function() {
				// показываем прогрессбар
		},
		complete: function() {
			// скрываем прогрессбар
		},			
		success: function(json) {
			console.log(json);
			handleAjaxSuccess(json.success)
			if(!handleAjaxError(json.error)) {
				if(json.success.redirect) document.location = json.success.redirect;
			}
			
		},
		error: function(xhr, ajaxOptions, thrownError) {
			console.log(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
			handleAjaxError({
				messages: [{
					title: 'Ошибка обмена данными',
					msg: 'Ошибка обработки запроса на стороне сервера. Обратитесь в службу поддержки',
				}],
			});
		}
	});
}


//--></script>

