<!DOCTYPE html>
<html>
    <head>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<meta name="description" content="<?php echo $controller->t->_("text_site_short_name"); ?>"/>
		<meta name="author" content="Porgiboy"/>
		<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
		<!-- для соцсетей 
		<meta property="og:image" content="http://<?php //echo $controller->config->application->host;?>/img/logo.png" />
		<meta property="og:title" content="Новость!" />
		<meta property="og:description" content="Опросы на сайте <?php //echo $controller->config->application->host;?>" />-->
		
		<!--<title>##Наименование сайта - служебная часть</title>-->
		
		<!--<link rel="shortcut icon" type="image/png" href="../../public/favicon.png"/>
		<link rel="shortcut icon" type="image/png" href="<?php //echo $controller->config->application->commonHost; ?>/favicon.png"/>-->
		
		<link rel="stylesheet" type="text/css" media="all" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"/>				
		<link rel="stylesheet" type="text/css" media="all" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.3.5/css/fileinput.min.css"/>
		<link rel="stylesheet" type="text/css" media="all" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" />				
		<link rel="stylesheet" type="text/css" media="all" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css">
		<link rel="stylesheet" type="text/css" media="all" href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.9/select2-bootstrap.min.css">
		<link rel="stylesheet" type="text/css" media="all" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/4.3.0/min/dropzone.min.css">
		<!--<link rel="stylesheet" href="../../lightbox-4.0.2/dist/ekko-lightbox.min.css" media="all" type="text/css"/>-->
		<link rel="stylesheet" type="text/css" media="all" href="../../stat.css"/>			
		
		<!--<link rel="stylesheet" href="../../botstrap-notify.css" media="all" type="text/css"/>-->
		<!--<link rel="stylesheet" href="../../js/jquery/jquery-ui-1.11.2.smothness/jquery-ui.css">-->
		
		<!-- jquery file-upload: загрузчик файлов в админке -->
		<!--<link rel="stylesheet" href="../../public\jQuery-File-Upload-9.12.5\css/jquery.fileupload.css">-->
		<!--<link rel="stylesheet" href="../../public\Gallery-2.21.3\css/blueimp-gallery.min.css">-->
		
		<!-- jquery ctNotify: везде -->
		<!--<link rel="stylesheet" href="../../js/jquery/ctNotify/lib/jquery.ctNotify.css">-->
		
		<!-- jquery ctNotify: меню в админке, вплывающие сообщения -->
		<!--<link rel="stylesheet" href="../../css/stylesheet.css">
		<link rel="stylesheet" href="../../css/my_css.css">-->
		
		<!-- jquery nailthumb: уменьшенные картинки -->
		<!--<link href="../../js/jquery/nailthumb/jquery.nailthumb.1.1.css" type="text/css" rel="stylesheet" />-->
		
		<!-- jquery yoxview: увеличение катинок для просмотра 
		<link href="../../js/jquery/yoxview/yoxview.css" type="text/css" rel="stylesheet" />
		<link href="../../js/jquery/yoxview/skins/top_menu/yoxview.top_menu.css" type="text/css" rel="stylesheet" />-->
		
		<!-- jquery magnific-popup: галерея -->
		<!--<link href="../../js/jquery/magnific-popup/dist/magnific-popup.css" type="text/css" rel="stylesheet" />-->

    </head>
    <body>
		
		<div class="container-fluid">
			<?php echo $this->getContent(); ?>
			
			<div class="row-fluid text-center">
				<hr>
				<a href="/"><?php echo $controller->t->_("text_site_short_name"); ?></a> &copy; 2016. Все права защищены.<br />Версия 0.2
			</div>
		</div><!-- /.container-fluid -->
		
		
		<!-- jquery: везде -->
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-json/2.6.0/jquery.json.min.js"></script>
		<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mouse0270-bootstrap-notify/3.1.5/bootstrap-notify.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/0.9.82/jsrender.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/js-sha1/0.3.0/sha1.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.3.5/js/fileinput.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.3.5/js/locales/ru.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/i18n/ru.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.5/validator.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/4.3.0/min/dropzone.min.js"></script>
		<!--<script type="text/javascript" src="../../public/lightbox-4.0.2/dist/ekko-lightbox.min.js"></script>-->
		
		<!--<script type="text/javascript" src="../../public\jQuery-File-Upload-9.12.5\js/vendor/jquery.ui.widget.js"></script>
		<script type="text/javascript" src="../../public\jQuery-File-Upload-9.12.5\js/jquery.fileupload.js"></script>
		<script type="text/javascript" src="../../public\jQuery-File-Upload-9.12.5\js/jquery.fileupload-process.js"></script>
		<script type="text/javascript" src="../../public\jQuery-File-Upload-9.12.5\js/jquery.fileupload-image.js"></script>
		<script type="text/javascript" src="../../public\jQuery-File-Upload-9.12.5\js/jquery.fileupload-validate.js"></script>-->
		
		
		
		<!-- для работы с модальными окнами --> 
		<script type="text/javascript" src="../../modal.js"></script>
		<script type="text/javascript" src="../../common.js"></script>
		<script type="text/javascript" src="../../templates/common_templates.js"></script>
		<script type="text/javascript" src="../../templates/scroller.js"></script>
		<script type="text/javascript" src="../../templates/entity.js"></script>
		<?php 
			$this->partial(APP_PATH . $this->config->application->commonTemplatesDir . "form_template");
			$this->partial(APP_PATH . $this->config->application->commonTemplatesDir . "scroller_template"); 
		?>
		
		<?php if($controllerName == "login" && $actionName == "index") {?>
			<script type="text/javascript"><!--
				$(document).ready(function() {
					formJQ = $("#loginForm");
					
					// делаем авторизацию на поле с паролем по нажатию Enter
					var passJQ = formJQ.find("#password");
					passJQ.focusin(function(){
						$(this).bind('keypress', function(e) {
							if(e.keyCode==13){
								backendLogin();
							}
						});
					}).focusout(function(){
						$(this).unbind('keypress', false);
					});
					
					// делаем переход из логина в поле с паролем по нажатию Enter
					var emailJQ = formJQ.find("#email");
					emailJQ.focusin(function(){
						$(this).bind('keypress', function(e) {
							if(e.keyCode==13){
								passJQ.focus();
							}
						});
					}).focusout(function(){
						$(this).unbind('keypress', false);
					});
				});
			//--></script>
		<?php } ?>
		
		<!--<script src="../../js/jquery/ui/i18n/jquery.ui.datepicker-ru.js"></script>-->
		<!--<script src="../../js/jquery/ui/i18n/jquery-ui-timepicker-addon-ru.js"></script>-->
				
		<!-- ckeditor: создание материалов -->
		<!--<script src="../../js/ckeditor/ckeditor.js"></script>-->
		<!--<script src="../../js/ckeditor/adapters/jquery.js"></script>-->
		
		<!-- jquery inputmask: поля формы авторизации-->
		<!--<script src="../../js/jquery/jquery.inputmask-3.x/inputmask/jquery.inputmask.js"></script>-->
		
		<!-- Яндекс-карты -->
		<!--<script src="//api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>-->
			
		
		<!--<script type="text/javascript" src="../../public\Gallery-2.21.3\js/blueimp-helper.js"></script>
		<script type="text/javascript" src="../../public\Gallery-2.21.3\js/blueimp-gallery.js"></script>
		<script type="text/javascript" src="../../public\Gallery-2.21.3\js/blueimp-gallery-fullscreen.js"></script>
		<script type="text/javascript" src="../../public\Gallery-2.21.3\js/blueimp-gallery-indicator.js"></script>
		<script type="text/javascript" src="../../public\Gallery-2.21.3\js/blueimp-gallery-video.js"></script>
		<script type="text/javascript" src="../../public\Gallery-2.21.3\js/blueimp-gallery-vimeo.js"></script>
		<script type="text/javascript" src="../../public\Gallery-2.21.3\js/blueimp-gallery-youtube.js"></script>
		<script type="text/javascript" src="../../public\Gallery-2.21.3\js/blueimp-gallery.min.js"></script>-->
    </body>
</html>