<!--<br>layouts\index-->
<?php $this->partial("partials/menu"); ?>
<?php //var_dump( $descriptor); ?>
<?php //var_dump( $dbg); ?>

<div class="row-fluid">
	<h1 class="page-header"><?php if(isset($page_header)) echo $page_header; ?></h1>
</div><!-- /.row-fluid -->

<div class="row-fluid">
	<div id="entity_form_placeholder"></div>
	<div id="scroller_form_placeholder"></div>
	
	<?php echo $this->getContent(); ?>
		
</div><!-- /.row-fluid -->

<script type="text/javascript"><!--
<?php if(isset($descriptor)) echo "var descriptor =" . json_encode($descriptor) . ";"; ?>
//--></script>


<div id="debug"></div>
